CC := g++
CFLAGS := -Wall -o

programa: 
	$(CC) $(CFLAGS)  main p03_string_operations_modified.cc file.cc cadenas.cc alfabetos.cc 

clean:
	rm -rf main_StringsOp main_alfabetos p03_string_operations_modified